version: "3.7"
services:
  go-server:
    build:
      context: go
      dockerfile: Dockerfile
    expose:
      - 5555
    volumes:
      - ./go:/code

  ruby-server:
    build:
      context: ruby
      dockerfile: Dockerfile
    expose:
      - 5555
    volumes:
      - ./ruby:/code

  server-proxy:
    image: envoyproxy/envoy:v1.14.4
    volumes:
      - ./envoy:/etc/envoy
    command: envoy -c /etc/envoy/server.yaml --service-cluster server-proxy
    ports:
      - 8000:8000
      - 8001:8081

  # client-proxy:
  #   image: envoyproxy/envoy:v1.14.4
  #   volumes:
  #     - ./envoy:/etc/envoy
  #   command: envoy -c /etc/envoy/client.yaml --service-cluster client-proxy
  #   expose:
  #     - 8000
  #   ports:
  #     - 7001:8081

  # ruby-client:
  #   build:
  #     context: ruby
  #     dockerfile: Dockerfile
  #   entrypoint: /code/client.rb
  #   volumes:
  #     - ./ruby:/code

  jaeger:
    image: jaegertracing/all-in-one
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=9411
    expose:
      - 9411
      - 14268
    ports:
      - 16686:16686

  oauth2-proxy:
    image: quay.io/oauth2-proxy/oauth2-proxy:v6.1.1
    environment:
      - OAUTH2_PROXY_CLIENT_ID=${ENVOY_AUTH_CLIENT_ID}
      - OAUTH2_PROXY_CLIENT_SECRET=${ENVOY_AUTH_CLIENT_SECRET}
      - OAUTH2_PROXY_COOKIE_SECRET=deadbeefdeadbeef
    ports:
      - 4180
    command:
      [
        "/bin/oauth2-proxy",
        "--provider=oidc",
        "--oidc-issuer-url=https://dev-283652.okta.com/oauth2/default",
        "--redirect-url=http://lvh.me/oauth2/callback",
        "--cookie-expire=4h",
        "--cookie-name=_oauth2_proxy_istio_ingressgateway",
        "--cookie-refresh=1h",
        "--cookie-samesite=lax",
        "--cookie-secure=false",
        "--email-domain=*",
        "--http-address=http://0.0.0.0:4180",
        "--upstream=static://200",
        "--skip-provider-button=true",
        "--whitelist-domain=lvh.me",
        "--set-authorization-header=true",
      ]
