#!/bin/bash

export PATH="$(go env GOTPATH)/bin:$PATH"

# @protoc -I api -I$(GOOGLEAPIS) -I$(SWAGGER) api/policies.proto --go_out=plugins=grpc:api/policies
protoc \
  -I ../proto \
  --go_out=plugins=grpc:. \
  --go_opt=paths=source_relative \
  ../proto/example.proto
